### PR TITLE
Fix support for linux on wine

### PR DESCRIPTION
**Pull request by PancakeTAS**
This is an odd one, but it appears that LoadLibraryEx at least in the current proton/wine version does not return a single long buffer and instead has some holes in it. I couldn't pinpoint where those holes where, but `IsBadReadPtr` is meant for exactly this purpose. With it in place the pattern search works again.

### CODE REVIEW

**Comment by PancakeTAS** [comment]
(this fixes #404)

**Comment by ethanaobrien** [comment]
Just wanted to chime in and say that I can confirm this patch works, built locally and works great! Thanks!

**Comment by 34736384** [comment]
IsBadReadPtr should not be used regardless, I will make an update shortly

**Comment by PancakeTAS** [comment]
> IsBadReadPtr should not be used regardless, I will make an update shortly

what do you suggest?

**Comment by 34736384** [comment]
fixed on https://github.com/34736384/genshin-fps-unlock/commit/4485c6a2bcce4ff2f1f82284222ade14f967b581

**Pull request closed without merging**
