### PR TITLE
Using hotkeys now requires holding combo key (default HOME)

### PR DESCRIPTION
**Pull request by Gornius**
Because for me arrow keys/END are common keys for everyday use and was changing FPS values whole the time. Simple and quick fix.

### CODE REVIEW

**Comment by 34736384** [comment]
I'm actually thinking about doing right control + arrow keys for changing the limit. Manually changing config file is not that of a big deal but it's not the most convenient way

**Comment by Lehner82** [comment]
Yeah, using Control would solve all issues pretty much

**Comment by Gornius** [comment]
> Yeah, using Control would solve all issues pretty much

Yeah "combo" key would be the best option, but IMO it shouldn't be Control, because I use it to move word-by-word in most text editors. Something that is never used together would be better, like Home + Arrows.

**Comment by Gornius** [comment]
Reversed previous changes and changed the code so now it requires holding "combo key" (my proposed HOME by default) before they change FPS values.

**Comment by 34736384** [comment]
> Reversed previous changes and changed the code so now it requires holding "combo key" (my proposed HOME by default) before they change FPS values.

Nice, I've been busy recently. I'll merge and update by the weekend

**Comment by 34736384** [comment]
> > Yeah, using Control would solve all issues pretty much
> 
> Yeah "combo" key would be the best option, but IMO it shouldn't be Control, because I use it to move word-by-word in most text editors. Something that is never used together would be better, like Home + Arrows.

For the control key I meant the right control key, not just control key in general. At least for me I never use the right control key

**Comment by Lehner82** [comment]
> > Reversed previous changes and changed the code so now it requires holding "combo key" (my proposed HOME by default) before they change FPS values.
> 
> Nice, I've been busy recently. I'll merge and update by the weekend

What about the update ?

**Comment by Gornius** [comment]
> > > Reversed previous changes and changed the code so now it requires holding "combo key" (my proposed HOME by default) before they change FPS values.
> > 
> > 
> > Nice, I've been busy recently. I'll merge and update by the weekend
> 
> What about the update ?

You can download my fork compiled or compile it yourself:
https://github.com/Gornius/genshin-fps-unlock/releases/tag/v1.4.0-gornius

**Pull request merged**
