### PR TITLE
Rewrite the application messages in a comprehensible manner

### PR DESCRIPTION
**Pull request by gridhead**
Rewrite the application messages in a comprehensible manner

### CODE REVIEW

**Comment by 34736384** [comment]
Everything else looks fine, just that instead of "videogame", using just "game" is fine, videogame sounds too old-school

**Comment by t0xic0der** [comment]
@34736384, agreed.

In my defence though, with the use of the word "videogame" - I was attempting to be specific about what the application is intended for. According to Wikipedia, the word ["Video game"](https://en.wikipedia.org/wiki/Video_game) falls more into the definition than the word ["Game"](https://en.wikipedia.org/wiki/Game), if that makes sense.

**Comment by t0xic0der** [comment]
@34736384, do you want me to change back the occurrences of the word "videogame" with just the word "game"? I can do that - just let me know :)

**Comment by 34736384** [comment]
project is going to be rewritten in net core, closing pr

**Pull request closed without merging**
