### PR TITLE
Fix DLL injection

### LINKED ISSUE #222: how to use dxvk in win10?
I tried to use the latest unlockfps.exe to inject dxgi.dll and d3d11.dll but it gives me "CreateRemoteThread failed with code:5"

### PR DESCRIPTION
**Pull request by vapopescu**
Fixes #222 #197
Inject DLL as soon as the process is launched. Injecting them later fails on `CreateRemoteThread()` with error code 5 "Access Denied".

Tested with 3DMigoto (GIMI) and ReShade.

### CODE REVIEW

**Comment by vapopescu** [comment]
Also fixes #197

**Comment by Scarlaid** [comment]
any chance a version with this patch available?
having this issue is so annoying, to the point that I have to remove and re-add the 3dmigoto dll everytime 😥

**Comment by vapopescu** [comment]
I published a release of my fork

**Comment by Scarlaid** [comment]
> I published a release of my fork

goated, ty man

**Comment by Scarlaid** [comment]
came back here to say this worked well as both 3dmigoto and specialK injected without any extra works
this deserve a merge, so it also have the "windows show in Alt-Tab" patch too

**Comment by Scarlaid** [comment]
Hey vapope, would you mind making your fork with the latest version (v2.1.3)?
On v2.1.1 there is a bug as Alt-Tab and Win-Tab showing a ghost window
image

Sorry if I have to ask here, your fork doesn't open issue nor discussion

**Comment by vapopescu** [comment]
I'd rather have @34736384 merge this already, but in the mean time I patched my fork with the latest version.

**Comment by Scarlaid** [comment]
thank you :)
judging by the activity and the response to one of the issue you linked for this PR, I don't think he will so better much to ask for your fork to be up-to-date than waiting, though annoying...

**Comment by 34736384** [comment]
was planned to rewrite the unlocker in net core, but I'll go ahead and merge this first

**Pull request merged**
